### ISSUE TITLE
Typings for Apollo are not correct

### ISSUE THREAD

**Issue by javi11** [confuser/graphql-constraint-directive#107]
Hey, we saw that typings as a Apollo plugin are not valid we see this error:

`
(alias) createApolloQueryValidationPlugin(): (schema: GraphQLSchema) => function
import createApolloQueryValidationPlugin
Type '(schema: GraphQLSchema) => function' is not assignable to type 'PluginDefinition'.
  Type '(schema: GraphQLSchema) => function' is not assignable to type '() => ApolloServerPlugin<BaseContext>'.ts(2322)
`

https://github.com/confuser/graphql-constraint-directive/blob/b139624b4a0ca63a593e83d1b34fec4a4cec24e6/index.d.ts#L10

shouldn't be like this?

```ts
export function createApolloQueryValidationPlugin({ schema: GraphQLSchema }) : PluginDefinition;
```

I can create a PR if you want

**Comment by confuser** [comment]
PRs welcome

**Comment by Yimiprod** [comment]
Hi, there's another problem with that type, the implementation is something like this
```js
const plugins = [createApolloQueryValidationPlugin({ schema })]
```

which is not what the type say

**Comment by Yimiprod** [comment]
@confuser i've put a PR in review if you like
