### ISSUE TITLE
[Help] How to make eslint graphql plugin know that custom directive

### ISSUE THREAD

**Issue by Yimiprod** [confuser/graphql-constraint-directive#108]
Hi

I use `@graphql-eslint/eslint-plugin` to validate my graphql files and the directive `@constraint()` is said unknow by it, which make ESlint throw an error.

How do i configure my graphqlconfig file to get the typedefs from graphql-constraint-directive ?

**Comment by confuser** [comment]
This isn't an issue with this library. Please ask the author of that module. A quick search shows they added supported: https://github.com/B2o5T/graphql-eslint/issues/833
