### ISSUE TITLE
Typescript support for @apollo/server V4

### ISSUE THREAD

**Issue by Yimiprod** [confuser/graphql-constraint-directive#128]
Apollo just release a [new major version](https://www.npmjs.com/package/@apollo/server) for Apollo Server making the typing of `createApolloQueryValidationPlugin` invalid.

The diff is like this:

```diff
- import {PluginDefinition} from "apollo-server-core";
+ import {ApolloServerPlugin} from '@apollo/server';

- export function createApolloQueryValidationPlugin ( options: { schema: GraphQLSchema } ) : PluginDefinition;
+ export function createApolloQueryValidationPlugin ( options: { schema: GraphQLSchema } ) : ApolloServerPlugin;
```

The plugin structure doesn't change tho. So maybe something like this would work:

```diff
- import {PluginDefinition} from "apollo-server-core";
+ import {ApolloServerPlugin} from "@apollo/server";

+ export function createApolloQueryValidationPlugin ( options: { schema: GraphQLSchema } ) : PluginDefinition | ApolloServerPlugin;
```

For anyone needing a temporary patch:

```ts
import { createApolloQueryValidationPlugin } from 'graphql-constraint-directive';

// temporary override type definition
type validationPluginFactory = (options: { schema: GraphQLSchema }) => ApolloServerPlugin;

const server = new ApolloServer({
  plugins: [
    (createApolloQueryValidationPlugin as validationPluginFactory)({ schema }),
  ],
});
```

**Comment by confuser** [comment]
PRs welcome :)

**Comment by velias** [comment]
@Yimiprod  Is it possible to make plugin compatible with both Apollo 3 and 4? I'd like to keep it compatible with both versions if possible.

**Comment by velias** [comment]
I'd like to patch it together with #131

**Comment by velias** [comment]
Yep, I'm going this direction as I also need to change error handling. 
But I'm not sure if in one ts file can be imports which are unsatisfied. I expect apollo 3 imports will be unsatisfied in case of apollo 4. Can you please somehow test it?
