### ISSUE TITLE
Building executable schema, for an Apollo subgraph

### ISSUE THREAD

**Issue by Tom-Pearce** [confuser/graphql-constraint-directive#132]
Hello,

This is less of an issue, more of a topic for documentation/suggested docs update.

I was trying to implement the constraint directive on an Apollo server instance, that is being used as a subgraph for my Apollo Gateway (and managed federations).

The Apollo specific documentation on the readme only talks about use in a standalone server that is not acting as a subgraph or microservice (or at least not hidden behind a gateway).

Specifically, Apollo has a [`buildSubgraphSchema` ](https://www.apollographql.com/docs/federation/api/apollo-subgraph/#buildsubgraphschema) function (that I believe uses `buildExecutableSchema` under the hood.

My typeDefs are imported from a file that looks like this:
```ts
import { gql } from 'apollo-server-core';

export const typeDefs = gql` SDL here `
```

Referencing the readme section on ApolloServer, you say you should build the schema like this:
```ts
let schema = makeExecutableSchema({
  typeDefs: [constraintDirectiveTypeDefs, typeDefs],
})
```

Now trying to apply the same logic to the `buildSugraphSchema` function like so:
```ts
import { typeDefs } from './schemas/schema';
import { resolvers } from './resolvers/resolver';
import { buildSubgraphSchema } from '@apollo/subgraph';
import {
    createApolloQueryValidationPlugin,
    constraintDirectiveTypeDefs
} from 'graphql-constraint-directive';
import { gql } from 'apollo-server-core';

const schema = buildSubgraphSchema({
    typeDefs: [constraintDirectiveTypeDefs, typeDefs],
    resolvers
});
```
Now this generates the following error:
```
Argument of type '{ typeDefs: (string | DocumentNode)[]; resolvers: { Query: { users: (_: undefined, { start, limit, cursor, pagination, orderBy, orderDir }: getUsersArgs) => Promise<User[]>; user: (_: undefined, args: getUserArgs) => Promise<...>; }; User: { ...; }; Mutation: { ...; }; }; }' is not assignable to parameter of type 'DocumentNode | (GraphQLSchemaModule | DocumentNode)[] | LegacySchemaModule'.
  Types of property 'typeDefs' are incompatible.
    Type '(string | DocumentNode)[]' is not assignable to type 'DocumentNode | DocumentNode[] | undefined'.
      Type '(string | DocumentNode)[]' is not assignable to type 'DocumentNode[]'.
        Type 'string | DocumentNode' is not assignable to type 'DocumentNode'.
          Type 'string' is not assignable to type 'DocumentNode'.ts(2345)
```

The solution to this as someone in the community found (thank you patrick.py):
```ts
import { typeDefs } from './schemas/schema';
import { resolvers } from './resolvers/resolver';
import { buildSubgraphSchema } from '@apollo/subgraph';
import {
    createApolloQueryValidationPlugin,
    constraintDirectiveTypeDefs
} from 'graphql-constraint-directive';
import { gql } from 'apollo-server-core';

const schema = buildSubgraphSchema({
    typeDefs: [gql(constraintDirectiveTypeDefs), typeDefs],
    resolvers
});
```
Note that I wrapped the `constraintDirectiveTypeDefs` with the `gql` tag.

I'm not sure if this is a trivial issue or something a little more subtle, but coming from a PHP background and transitioning into typescript and using node/express/GQL/Apollo, this threw me for a couple days so wanted to document it for others. (Maybe I'm trying to learn too much at once who knows, I'm just hoping to save someone else the headache)

This resolves all the issues, the subgraph will now compose with the `constraint` directive working. The only caveat is I am using Apollo Server v4.0 and at time of writing the plugins parameter has a type mismatch, as documented in issue #128

**Comment by confuser** [comment]
Thanks @Tom-Pearce, would you be willing to open a PR to add this to the documentation?
