### ISSUE TITLE
Constraint validation fails requires apollo-server for errors in @apollo/server v4

### ISSUE THREAD

**Issue by IgorSSilveira** [confuser/graphql-constraint-directive#136]
'@apollo/server' v4 removed the 'ApolloError' classes, so whenever a constraint validation fails it throws the following error out: 

```json
{
  "data": {},
  "errors": [
    {
      "message": "Cannot find module 'apollo-server-errors'\nRequire stack:\n- C:\\Users\\user\\Desktop\\projects\\node_apollo_server_intro\\node_modules\\graphql-constraint-directive\\index.js\n- C:\\Users\\user\\Desktop\\projects\\node_apollo_server_intro\\app.js",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Migration to v4 using 'GraphQLError' is documented [here](https://www.apollographql.com/docs/apollo-server/migration#apolloerror).

I have tried changing the code that throws 'UserInputError' to throw a GraphQLError in [createApolloQueryValidationPlugin](https://github.com/confuser/graphql-constraint-directive/blob/master/index.js):

```javascript
if (errors.length > 0) {
  throw errors.map(err => {
    return new GraphQLError(err.message, {
        extensions: {
        field: err.fieldName,
        context: err.context,
        code: "BAD_USER_INPUT",
      },
    })
  })
}
```
The response changes to: 

```json
{
  "data": {},
  "errors": [
    {
      "message": "Unexpected error value: Variable \"$input\" got invalid value \"A string that is longer than 25 characters\" at \"input.nome\". Must be no more than 25 characters in length",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
It still throws an "INTERNAL_SERVER_ERROR" and adds "Unexpected error value: " to the error message.

v4 seems to also add a function in [errorNormalize.ts](https://github.com/apollographql/apollo-server/blob/main/packages/server/src/errorNormalize.ts), it normalizes the errors that are thrown, checking for the type:

```javascript
function ensureError(maybeError) {
    return maybeError instanceof Error
        ? maybeError
        : new graphql_1.GraphQLError('Unexpected error value: ' + String(maybeError));
}
```

The GraphQLError thrown before is not an 'Error' as the array is what is actually being thrown in 'createApolloQueryValidationPlugin', 
so for the extensions to go through and not be replaced by "INTERNAL_SERVER_ERROR", it is needed to throw just the error, not the array.

**Comment by joaop221** [comment]
@confuser can you check this?

**Comment by velias** [comment]
It is somehow related to #131 as whole Errors used by this plugin should be cleared up. It is also related to #128 . I'd like to patch this in the near future.

**Comment by velias** [comment]
Hmm, problem is that query validation can return multiple errors. So question is how to correctly return them from the plugin's `didResolveOperation` if possible.

**Comment by confuser** [comment]
Not sure why the Apollo team removed support for throwing multiple errors, however @velias it should be possible to return them using extensions https://www.apollographql.com/docs/apollo-server/data/errors/#including-custom-error-details

**Comment by velias** [comment]
@confuser yep, this is exactly how I implemented it in #147. If there is only one validation error it is returned directly, if more then top level error is generic and contains exact errors in `extensions.validationErrors`. Documented in `README.md`.

**Comment by elainegasca** [comment]
¿Any update about this?

**Comment by velias** [comment]
PR is ready, waiting for owner to merge it

**Comment by joaop221** [comment]
@confuser pls
