### ISSUE TITLE
Is there a way to annotate a directive to all the generated scalars ?

### ISSUE THREAD

**Issue by BahaaZidan** [confuser/graphql-constraint-directive#137]
I'm implementing fine control over introspection. This requires me to annotate all the types/fields that I want to be visible to the introspection query with a `@public` directive. This of course includes the scalars generated by the constraint library. So is there a way to annotate the generated validation scalars with a directive ?

**Comment by velias** [comment]
If you can use second implementation from this plugin (server plugins/extensions), then there are no custom scalars generated, so no problem for you ;-).

For the schema wrapping implementation with custom scalars I have no idea.
