### ISSUE TITLE
Help understanding code

### ISSUE THREAD

**Issue by monvillalon** [confuser/graphql-constraint-directive#143]
Fell free to close this since its not an issue per-se but advice.

I find myself having to do something similar to `graphql-constraint-service` so I've been reading and testing your package.
In my use case I need to apply html validation to all the strings in the graphql schema and then use a directive to selectively turn off the sanitation .

I've independently seemed to have reached the same approach as you, by doing a custom scalar type and use a transformer to change all strings into my new scalar that does the sanitation. 

However I know I find myself breaking backwards compatibility and having to update all queries on all clients to use my new scalar `SantizedString` instead of `String`, some of which I don't control.

I see that package doesn't have that issue when I install the apollo plugin, but I fail to understand how it addresses the problem and the internet has given me no clues.

Any help or explanation would be greatly appreciated.

**Comment by velias** [comment]
Apollo plugin approach do not use schema transformation. It installs GraphQL server side extension/plugin which is invoked by server during query processing and performs necessary validations.
