### ISSUE TITLE
Add support to optional fields

### ISSUE THREAD

**Issue by judielr** [confuser/graphql-constraint-directive#16]
Actually it's impossible to use constraints with optional values.

For example: 
this doesn't work if `birth_date` is not present
```
input UserInput {
  name: String @constraint(minLength: 2),
  surname: String @constraint(minLength: 2),
  dni: String,
  birth_date: String @constraint(format: "date")
}
```

And this would be awesome!

```
input UserInput {
  name: String @constraint(minLength: 2, optional:true),
  surname: String @constraint(minLength: 2, optional:true),
  dni: String,
  birth_date: String @constraint(format: "date", optional:true)
}
```

I think this improve would increase the package capabilities .

Thanks!

**Comment by williamkwao** [comment]
@confuser I was going through the code to figure out why this is not working for optional fields but I couldn't find why this is happening. I'll take a good look again to see whats going on. If you can give me a brief explanation on why this is happening, I'll make a PR for this issue.

**Comment by confuser** [comment]
@williamkwao most likely to do with checking for NonNull fields https://github.com/confuser/graphql-constraint-directive/blob/master/index.js#L53 Should probably pass in an argument to the String/Number field types to check whether a value is required or not

**Comment by williamkwao** [comment]
@confuser Thanks!  I'll take a stab at it.  If that is the case, shouldn't it default to the conditional without the GraphQLNonNull check?  https://github.com/confuser/graphql-constraint-directive/blob/11b01363b9151814efe4598e7dad48ffd5934181/index.js#L55

**Comment by madarco** [comment]
Any updates on this issue? Thanks!
