### ISSUE TITLE
Possible to mix transform (schema wrapping) and plugin?

### ISSUE THREAD

**Issue by robross0606** [confuser/graphql-constraint-directive#161]
We have a published schema which is already using the schema wrapping method for constraints in several places.  We would like to start migrating towards the plugin mechanism.  However, swapping them out will instantly change the types of previously existing wrapped types.  This effectively breaks the schema for API clients, which is something we're not allowed to do.  It would be extremely useful if there were a way to annotate which directives were to be handled by the wrapper and which were to be handled by the plugin so that this can be controlled strategically (deprecation, etc.).

**Comment by velias** [comment]
Hmm, I think crucial here is how to distinguish which field is handled by which implementation.
Maybe easier should be to fully switch to plugin, and only make sure that previous existing types still exist, without validation logic. It should be achieved by use of `uniqueTypeName` which will be added to all existing constraints with existing names, then writing wrapper transformer for it. Or maybe even use current wrapper transformer, and only disable validation logic in it.
