### ISSUE TITLE
Error: Unknown directive "@constraint".

### ISSUE THREAD

**Issue by sohaibMan** [confuser/graphql-constraint-directive#165]
I am reciving this error (Error: Unknown directive "@constraint")  even I've follow the docs
## code example
```
//path to schema from this folder
const schemaPath = path.join(rootPath, "/schema/*.graphql");
// console.log("🚀 ~ file: index.ts:9 ~ schemaPath:", schemaPath)
const typeDefs = loadSchemaSync(schemaPath, { loaders: [new GraphQLFileLoader()] })

let schema = makeExecutableSchema({
  typeDefs: [constraintDirectiveTypeDefs, typeDefs],
})

const plugins = [
  createApollo4QueryValidationPlugin({
    schema
  })
]

const server = new ApolloServer({
  schema,
  plugins
})
```
## scehma example 
```
type Project {
  #   client_id: ObjectID
  _id: ObjectID
  title: String! @constraint(minLength: 5, maxLength: 100)
  description: String! @constraint(minLength: 5, maxLength: 1000)
  price: Float! @constraint(min: 0)
  skills: [String!]! @constraint(maxItems: 15)
  reactions: Reactions!
  created_date: Date!
  projectScope: ProjectScopeOutput!
  AttachmentsURL: [Attachment]
}
```

I am using nextJs and apollo graphql 4

**Comment by Holubinka** [comment]
I have the same error

**Comment by sohaibMan** [comment]
Try to add this to your schema 
```
directive @constraint(
  # String constraints
  minLength: Int
  maxLength: Int
  startsWith: String
  endsWith: String
  contains: String
  notContains: String
  pattern: String
  format: String
  # Number constraints
  min: Float
  max: Float
  exclusiveMin: Float
  exclusiveMax: Float
  multipleOf: Float
  # Array/List size constraints
  minItems: Int
  maxItems: Int
  # Shared for Schema wrapper
  uniqueTypeName: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION | ARGUMENT_DEFINITION
```

**Comment by Holubinka** [comment]
> Try to add this to your schema
> 
> ```
> directive @constraint(
>   # String constraints
>   minLength: Int
>   maxLength: Int
>   startsWith: String
>   endsWith: String
>   contains: String
>   notContains: String
>   pattern: String
>   format: String
>   # Number constraints
>   min: Float
>   max: Float
>   exclusiveMin: Float
>   exclusiveMax: Float
>   multipleOf: Float
>   # Array/List size constraints
>   minItems: Int
>   maxItems: Int
>   # Shared for Schema wrapper
>   uniqueTypeName: String
> ) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION | ARGUMENT_DEFINITION
> ```
Need to add constraintDirectiveTypeDefs in code together with own typeDefs?

**Comment by sohaibMan** [comment]
@Holubinka  just follow the docs in the server creation here is an example :
```

// load schema
let schema = loadSchemaSync(schemaPath, {
  loaders: [new GraphQLFileLoader()],
});

schema = constraintDirective()(schema)

// create an apollo server instance
const server = new ApolloServer<ServerContext>({
  typeDefs: [constraintDirectiveTypeDefs, schema],
  resolvers: [YourResolver],
});
```

**Comment by sohaibMan** [comment]
> > Try to add this to your schema
> > ```
> > directive @constraint(
> >   # String constraints
> >   minLength: Int
> >   maxLength: Int
> >   startsWith: String
> >   endsWith: String
> >   contains: String
> >   notContains: String
> >   pattern: String
> >   format: String
> >   # Number constraints
> >   min: Float
> >   max: Float
> >   exclusiveMin: Float
> >   exclusiveMax: Float
> >   multipleOf: Float
> >   # Array/List size constraints
> >   minItems: Int
> >   maxItems: Int
> >   # Shared for Schema wrapper
> >   uniqueTypeName: String
> > ) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION | ARGUMENT_DEFINITION
> > ```
> 
> Need to add constraintDirectiveTypeDefs in code together with own typeDefs?
@Holubinka just follow the docs in the server creation here is an example :


// load schema
let schema = loadSchemaSync(schemaPath, {
  loaders: [new GraphQLFileLoader()],
});

schema = constraintDirective()(schema)

// create an apollo server instance
const server = new ApolloServer<ServerContext>({
  typeDefs: [constraintDirectiveTypeDefs, schema],
  resolvers: [YourResolver],
});

**Comment by Holubinka** [comment]
> @Holubinka just follow the docs in the server creation here is an example :

Thanks for help
