### ISSUE TITLE
originalError is undefined

### ISSUE THREAD

**Issue by thijssteel** [confuser/graphql-constraint-directive#18]
When trying to customise the error, i seem to be unable to access the originalError property.

Using the following function as error formatter
```
const formatError = (error: GraphQLError) => {
  console.log('original error', error.originalError)
  return error
}
```

Simply logs `original error {}` to the console.

I was able to access the original error when using node-graphql-constraint-lambda, but they don't seem to throw custom errors, so it might just be a problem with apollo/graphql.

I'm using graphql@14.4.2 and apollo-server-express@2.8.1

Edit: here is a minimal example:
```
const ConstraintDirective = require('graphql-constraint-directive')
const express = require('express')
const { ApolloServer } = require('apollo-server-express')

const formatError = (error) => {
  console.log('original error', error.originalError)
  return error
}


const typeDefs = `
  directive @constraint(
    # String constraints
    minLength: Int
    maxLength: Int
    startsWith: String
    endsWith: String
    notContains: String
    pattern: String
    format: String

    # Number constraints
    min: Int
    max: Int
    exclusiveMin: Int
    exclusiveMax: Int
    multipleOf: Int
  ) on INPUT_FIELD_DEFINITION

  type Query {
    books: [Book]
  }
  type Book {
    title: String
  }
  type Mutation {
    createBook(input: BookInput): Book
  }
  input BookInput {
    title: String! @constraint(minLength: 5, format: "email")
  }`


const resolvers = {
  Mutation: {
    createBook: () => ({title:'Hello world!'}),
  },
};
const server = new ApolloServer({ typeDefs, resolvers, schemaDirectives: { constraint: ConstraintDirective }, formatError });
const app = express()
server.applyMiddleware({ app });

app.listen({ port: 8080 }, () =>
  console.log(`🚀 Server ready at http://localhost:8080${server.graphqlPath}`)
);
```

**Comment by thijssteel** [comment]
Ok, i have been debugging this and i've finally found the answer.
Because the originalError property is not enumerable, it doesn't show up when console logging. Because of this i missed the fact that the original error is actually located at `error.originalError.originalError`

**Comment by confuser** [comment]
It shouldn't be located in `error.originalError.originalError`, there is a test case covering this https://github.com/confuser/graphql-constraint-directive/blob/master/test/string.test.js#L58-L73 unless this is an issue with a newer version of apollo? Which version are you using?

As for it not being enumerable, I'm not sure if that can be resolved in this module, as the error is wrapped by apollo-server.
