### ISSUE TITLE
feat: "Custom Validator via Callback"

### ISSUE THREAD

**Issue by ichtestemalwieder** [confuser/graphql-constraint-directive#22]
Hallo, 

thanks for the great project. Please also provide  a Validator, that allows to specify a callback/anonymous function that is used for validation, so one can easily create custom complex validation logic on the fly. 

Thanks very much.

**Comment by confuser** [comment]
What would be the benefit of this over doing the validation in a resolver function?

**Comment by ichtestemalwieder** [comment]
Thanks for your reply! I am new to TS/GraphQL. Realilzing now, that most likely it makes more sense to write a whole new contraint directive (when used multiple times) or include it in the resolver (when used one time). Sorry for opening an issue.
