### ISSUE TITLE
directives not working with apollo-server-lambda

### ISSUE THREAD

**Issue by hashinclude72** [confuser/graphql-constraint-directive#24]
constraints are not working with [apollo-server-lambda](https://www.apollographql.com/docs/apollo-server/deployment/lambda/).

Not giving any errors and queries are getting executed.

**Comment by sandromartis** [comment]
Are you using `visitSchemaDirectives`?

Try something like this:
```js
const { ApolloServer } = require("apollo-server-lambda");
const { SchemaDirectiveVisitor } = require("graphql-tools");
const ConstraintDirective = require("graphql-constraint-directive");

const schemaDirectives = { constraint: ConstraintDirective };

SchemaDirectiveVisitor.visitSchemaDirectives(schema, schemaDirectives);

const server = new ApolloServer({
  schema,
  context,
});

exports.graphqlHandler = server.createHandler({});
```

**Comment by hashinclude72** [comment]
Thanks for replying, still not working though, I am doing something like this : 
Not sure if I am doing it right

```javascript
const { ApolloServer } = require("apollo-server-lambda");
const { makeExecutableSchema, SchemaDirectiveVisitor } = require("graphql-tools");
const ConstraintDirective = require("graphql-constraint-directive");
const resolvers = require('./resolvers');
const typeDefs = require('./schema');

const schema = makeExecutableSchema({
    typeDefs,
    resolvers
});
const schemaDirectives = { constraint: ConstraintDirective };

SchemaDirectiveVisitor.visitSchemaDirectives(schema, schemaDirectives);

const server = new ApolloServer({
  schema,
  context,
});

exports.graphqlHandler = server.createHandler({});
```

I have `typeDefs` and `resolvers` on diffferent files.

**Comment by wdalmut** [comment]
i finally ends up here. Same problem no validation occurs with apollo and lambda functions

**Comment by alejalapeno** [comment]
```
scalar ConstraintString
scalar ConstraintNumber
```
These scalar types in the example definition were preventing validation for me.

If you've included them in your `typeDefs` try removing them.

**Comment by igrek8** [comment]
Make sure the resulting `typeDefs` contains `@directive`. Otherwise, the directive will be applied. See https://github.com/dotansimha/graphql-code-generator/issues/3899
