### ISSUE TITLE
apollo server version 2

### ISSUE THREAD

**Issue by hashinclude72** [confuser/graphql-constraint-directive#38]
hi, i just wanted to confirm that does this package works with `apollo-server` v2 because in lot of forums its written it does't but also those comments are fairly old.
 
If it does work with v2, its not working for me , i have done something like this 🤷‍♂️ :

```js
import schema from './schema';
import resolvers from './resolvers';
import { ApolloServer, makeExecutableSchema } from 'apollo-server-express';
import { constraintDirective, constraintDirectiveTypeDefs } from 'graphql-constraint-directive';

const server = new ApolloServer({
	introspection: true,
	playground: true,
	schema: makeExecutableSchema({
		typeDefs: [constraintDirectiveTypeDefs, ...schema],
		resolvers,
		schemaTransforms: [constraintDirective()],
	}),
});
```
please help 👱‍♂️

**Comment by confuser** [comment]
Yes it works, tests are all passing. Any particular reason you're using the spread operator on your schema?

**Comment by hashinclude72** [comment]
Thats because my schema is already a array of schemas from diff files.

OK now it works because i imported `makeExecutableSchema` from `graphql-tools` , but i have to install that package only for this purpose. It id not working if i import `makeExecutableSchema` from `apollo-server` .

BTW thanks for the reply 🙆‍♂️
