### ISSUE TITLE
Feature request: add the constraint details to field description

### ISSUE THREAD

**Issue by koresar** [confuser/graphql-constraint-directive#4]
Here is my input field declaration (I'm using SDL files):
```graphql
    """
    Account number. Only digits are allowed.
    """
    accountNo: String @constraint(minLength: 6, maxLength: 64, pattern: "^[0-9]*$")
```

Here is my declaration of the `ConstraintString` type:
```graphql
"""
Usual string but with some additional contraints
"""
scalar ConstraintString
```

Here is how it looks in a schema browser:
![image](https://user-images.githubusercontent.com/1622575/42358030-07856f5c-811e-11e8-81ca-6ae7ccef9e43.png)

Please note this bit:
> Account number. Only digits are allowed.

### Feature

Is it possible to add info about the actual constraints (min/max length and RegEx string)?

So that the description would be this:
> Account number. Only digits are allowed.
> Constraints:
> Minimum string length: `6`
> Maximum string length: `64`
> String should match RegEx: `^[0-9]*$`

Reminder. The GraphQL field description can use CommonMark: http://commonmark.org/

**Comment by velias** [comment]
I like this idea and might implement it ;-) Probably as a separate schema transformer, so can be used with the server validation plugins also.
