### ISSUE TITLE
Is there any way to make this library work alongside Apollo federation?

### ISSUE THREAD

**Issue by grillorafael** [confuser/graphql-constraint-directive#41]
I didn't find a way to have makeExecutableSchema work alongside Apollo-federated. Is there any way to use this library while using Apollo federation?

**Comment by robross0606** [comment]
There are multiple tickets opened with this same question.  I also have this question.  I've been able to get the federated schema to show the constraint directive in it.  There are no errors at startup and no complaints about my declaration or usage of @constraint in the schema.  However, no errors are thrown when testing constraint violations either.  It simply doesn't do anything.

**Comment by robross0606** [comment]
I thought I was able to get this working by executing the transform after building the federated schema.  This produced all the expected behaviors.  However, I just found that the transform wipes out `__resolveReference()` functions on the resolvers, rendering entity type resolution non-operational.  I'm back to square one with using this.  It would be _really_ nice if contributors could at least acknowledge this ticket in some way.

**Comment by confuser** [comment]
@robross0606 Sorry for your frustrations, I haven't used Apollo federation. Thanks for looking into it, it would be great if you could share your changes so once https://github.com/ardatan/graphql-tools/issues/2687 is resolved this can subsequently be resolved quickly

**Comment by robross0606** [comment]
@confuser, the example jest test on ardatan/graphql-tools#2687 shows how I execute the transform _after_ building the federated schema.

**Comment by confuser** [comment]
I believe this is now resolved with the latest v4 release

**Comment by robross0606** [comment]
I went to go try this and noticed this in the README:

> For GraphQL v15 and below, use v2 of this package
> 
> npm install graphql-constraint-directive@v2

This means using the input validation plugin instead of schema wrapper is only compatible with GraphQL 16?  Is that right?
