### ISSUE TITLE
Directive Doesn't Work When using `makeExecutableSchema` from "apollo-server-express"

### ISSUE THREAD

**Issue by mstmustisnt** [confuser/graphql-constraint-directive#48]
The directive makes no effect when used with `makeExecutableSchema` from "apollo-server-express"
In the screenshot below you can see that we expect the email string of length >5 as a title and limit >0
As you can see, limit: -1 and title: "st" are allowed, although they shouldn't pass the validation.
![image](https://user-images.githubusercontent.com/13254351/98644454-25d8b800-2339-11eb-809d-9db5fed446fe.png)

When I switched to @graphql-tools/schema makeExecutableSchema, everything works
![image](https://user-images.githubusercontent.com/13254351/98644709-91228a00-2339-11eb-8fd1-2c5424577441.png)

**Comment by Axighi** [comment]
I got same issue. Switch to @graphql-tools/schema makeExecutableSchema works.

**Comment by confuser** [comment]
I believe this is expected, the readme indicates `makeExecutableSchema` from graphql-tools must be used as well
