### ISSUE TITLE
formatError in the README isn't working with Apollo Stack 2

### ISSUE THREAD

**Issue by koresar** [confuser/graphql-constraint-directive#5]
This `if` clause doesn't work with Apollo Stack 2. (Haven't checked v1. Sorry.)
```js
  if (error.originalError && error.originalError.code === 'ERR_GRAPHQL_CONSTRAINT_VALIDATION') {
    // return a custom object
  }
```

But this one works:
```js
if (error.originalError.errors.some(e => e.originalError.code === 'ERR_GRAPHQL_CONSTRAINT_VALIDATION')) {
    // return a custom object
}
```

This is a good thing, because if `@constraint` found several violations in your mutation then all of them will be returned, not just the first one.

**Comment by confuser** [comment]
Just come across the same issue with Apollo 2 as well but noticed there was no `errors` array on originalError. Instead they appeared to be nested, perhaps due to not using `makeExecutableSchema`, had to use the following

```js
const findOriginalError = (error) => {
  if (error.originalError) return findOriginalError(error.originalError)

  return error
}

formatError (error) {
  const originalError = findOriginalError(error)

  if (originalError.code === 'ERR_GRAPHQL_CONSTRAINT_VALIDATION') {
    // return a custom object
  }
}
```
