### ISSUE TITLE
Allow detecting null

### ISSUE THREAD

**Issue by davidgilbertson** [confuser/graphql-constraint-directive#56]
I would like to able to assert that a field on an input is optional, but not nullable (so I can do a partial update of an entity). [GraphQL has no such syntax](https://github.com/graphql/graphql-spec/issues/542) so I was hoping I could use this dirctive for that.

Something like:
```graphql
input UpdateUser {
  id: ID!
  username: String @contraint(notNull: true)
  password: String @contraint(notNull: true)
}
```

Is this possible?

**Comment by confuser** [comment]
Not possible with GraphQL itself (https://github.com/graphql/graphql-spec/issues/476) but might be possible to support via a directive. However, I'm not sure it fits in with this library; happy to be challenged though.

**Comment by robross0606** [comment]
I personally think this definitely fits into the goals of this library.  The problem space here is an [old one](https://github.com/graphql/graphql-spec/issues/542).  If you're providing inputs (type fields, not mutation parameters) that are optional, you need to be able to say "if provided, this field cannot be null."  GraphQL does not currently distinguish between "required" and "non-nullable".  That sure feels like an input constraint to me.

**Comment by JannikWempe** [comment]
> If you're providing inputs (type fields, not mutation parameters) that are optional, you need to be able to say "if provided, this field cannot be null."

This is a very common use case for partial updates that include fields that should not be set to explicit `null`. Leaving field out of partial update is fine though and leaves the field untouched.
