### ISSUE TITLE
Separate modules and constraint not working

### ISSUE THREAD

**Issue by ErnestoCamilo** [confuser/graphql-constraint-directive#70]
I have the following configuration on my server
![image](https://user-images.githubusercontent.com/89998025/132005477-c5dc0165-aec3-437f-a694-cf29a2fb2717.png)
Each module export 
![image](https://user-images.githubusercontent.com/89998025/132005601-fc0cc3ee-eb60-4975-b74e-bf92ada2b6de.png)
And the configuration on schema 
![image](https://user-images.githubusercontent.com/89998025/132005770-51794f6d-5938-44e6-9efb-eee2f070ae65.png)
But the validation of field not working for me. 
what i'm missing

**Comment by confuser** [comment]
What version of Apollo are you using?
