### ISSUE TITLE
@constraint directive not working after upgrading to Apollo Server 3

### ISSUE THREAD

**Issue by vinaybishnoi29** [confuser/graphql-constraint-directive#71]
After upgrading apollo-server 3, the constraint directive is not working.
I have upgraded apollo-server to 3.3.0, graphql-tools to 8.1.0 and graphql-constraint-directive to 2.1.1

Do we have plans to support Apollo server 3 upgrades?

**Comment by gsaini** [comment]
+1

**Comment by vespaiach** [comment]
I found that the `schemaTransforms` option doesn't exist on `makeExecutableSchema` parameters. You have to call `constraintDirective` function directly and pass the `schema` into it. 

Here is example:

```
import { ApolloServer } from 'apollo-server';
import { makeExecutableSchema } from '@graphql-tools/schema';
import { constraintDirective, constraintDirectiveTypeDefs } from 'graphql-constraint-directive';

import { typeDefs } from 'src/schema/definition';
import { resolvers } from 'src/resolver';

const schema = makeExecutableSchema({
  typeDefs: [constraintDirectiveTypeDefs, typeDefs],
  resolvers,
});

const server = new ApolloServer({
  schema: constraintDirective()(schema), // call directly
});
```

**Comment by confuser** [comment]
I'm not up-to-date with Apollo major releases, but it appears to be a Usage issue rather than needing internal changes based on @vespaiach's investigation. Can others confirm this is the case?

**Comment by vinaybishnoi29** [comment]
> @vinaybishnoi29 I found that the `schemaTransforms` option doesn't exist on `makeExecutableSchema` parameters. You have to call `constraintDirective` function directly and pass the `schema` into it explicitly.
> 
> Here is example:
> 
> ```
> import { ApolloServer } from 'apollo-server';
> import { makeExecutableSchema } from '@graphql-tools/schema';
> import { constraintDirective, constraintDirectiveTypeDefs } from 'graphql-constraint-directive';
> 
> import { typeDefs } from 'src/schema/definition';
> import { resolvers } from 'src/resolver';
> 
> const schema = makeExecutableSchema({
>   typeDefs: [constraintDirectiveTypeDefs, typeDefs],
>   resolvers,
> });
> 
> const server = new ApolloServer({
>   schema: constraintDirective()(schema), // call directly
> });
> ```

@vespaiach I tried this and it works fine. Thanks for the prompt reply.

**Comment by vinaybishnoi29** [comment]
@confuser The usage changes mentioned by @vespaiach fixed the issue and the constraint directive works now.
Thanks for the prompt reply.
