### ISSUE TITLE
min value validation throws errors

### ISSUE THREAD

**Issue by anjith-sm** [confuser/graphql-constraint-directive#78]
When I tried to give min value constraint value as 0.01 got the below error:

_Argument "min" has invalid value 0.01._

Input looks like this:

input someInput {
  someId: ID!
  someValue: Float! @constraint(min: 0.01, max: 3)
}

**Comment by confuser** [comment]
This will be because the `constraintDirectiveTypeDefs` definition has min/max as an Int rather than a Float. You can work around this by performing a string replace before adding it to your schema but understand this seems rather 'hacky'. Open to suggestions and/or PRs!
