### ISSUE TITLE
`constraintDirectiveTypeDefs` should be a `DocumentNode` ?

### ISSUE THREAD

**Issue by BarbecueSilver** [confuser/graphql-constraint-directive#84]
Hej there!

Thanks for this project. :smile::+1: 

I just tried to update your package from `2.1.1` to `2.3.0` and noticed that `constraintDirectiveTypeDefs` is a `string`.
Shouldn't it be a gql `DocumentNode`?

Kind regards :wave:

**Comment by confuser** [comment]
The TypeScript definitions were added in #68, happy to accept a PR if they're not correct
