### ISSUE TITLE
Unexpected token '.' version 3.0.0

### ISSUE THREAD

**Issue by oxo0300** [confuser/graphql-constraint-directive#87]
@confuser 
node_modules/graphql-constraint-directive/index.js:116
const directiveArgumentMap = getDirective(schema, fieldConfig, 'constraint')?.[0]

**Comment by oxo0300** [comment]
Possible Fix
const directiveArgumentMap = getDirective(schema, fieldConfig, 'constraint')?[0];

**Comment by confuser** [comment]
Hi @oxo0300, this is using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which is supported as of Node 14+. Given the current LTS is 16, I'd recommend updating your nodejs version if possible.

If not and are not yet using graphql v16, feel free to continue using v2 of this package
