### ISSUE TITLE
Is there a way to have nullable field with constraint?

### ISSUE THREAD

**Issue by maxbarbul** [confuser/graphql-constraint-directive#88]
```graphql
input UpdatePost {
  # ...
  content: String
  excerpt: String @constraint(maxLength: 1000)
}
```

with the schema in the example above, I'm unable to send `null` as a value for `excerpt` because constraint asserts string type. Basically, the field became mandatory.

**Comment by confuser** [comment]
Hi @maxbarbul, you should be able to send null. I've just added some explicit tests showing this
