### ISSUE TITLE
Constrainting GraphQL ID type

### ISSUE THREAD

**Issue by koresar** [confuser/graphql-constraint-directive#9]
Do you think it's reasonable to use this directive for GraphQL `ID` type?
```
input OrderInput {
  fromFacilityId: ID @constraint(minLength: 24, maxLength: 24)
  toFacilityId: ID @constraint(minLength: 24, maxLength: 24)
}
```

The only caveat here - ID can be both string and number.

I'd be happy to PR this feature.

**Comment by confuser** [comment]
Not sure I agree if it's necessarily beneficial to do instead of a custom scalar, but happy to accept a PR for it

**Comment by koresar** [comment]
Hm... How to validate a customised scalar? I didn't know it's possible.

**Comment by confuser** [comment]
In a similar way this module works (minus the directive part). Create a custom scalar, perform your validation checks within `serialize`, `parseValue`, `parseLiteral` (depending on use case) and throw if it fails.

**Comment by koresar** [comment]
Got it. Sounds like this directive is a good place for such a code.

I'll allocate some time for the pr.

Thank you for the help.

**Comment by kristianmandrup** [comment]
Any progress on this?

**Comment by robross0606** [comment]
I'm shocked this isn't supported already.  But I also think there is some miscommunication involved.  `ID` cannot be a number.  It is a standard GraphQL scalar type, not custom.  It is purely a string with extra implied semantics:

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

**Comment by robross0606** [comment]
The use case here is very simple.  It is very common to require an `ID` as input on a query or mutation.  The constraint would be to dictate the minimum length or even pattern of the ID.  No different than the use cases for `String` input, really.
