### ISSUE TITLE
Feature Request: run as server validation rules instead of wrapping schema types

### ISSUE THREAD

**Issue by velias** [confuser/graphql-constraint-directive#92]
Allow to run query validations as [server validation rules](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#validationrules) instead of wrapping types in schema.

@confuser I can try to contribute this feature if you would be open to merge it.

**Comment by confuser** [comment]
Hi @velias. Thanks for the suggestion. I'm not familiar with the validationRules option, could you enlighten me on what this would help achieve with this module? 🙂

**Comment by velias** [comment]
This approach allows to keep Schema as is, without changing types to custom scalars. So in schema there will be common String or Int, but query validation will be applied to it still.

`validationRules` are simply server side code run during the query validation phase, they have access to complete query but also Schema with directives, so they can validate query against constraints set by the directives.

They work in more servers, beside Apollo they should work in express-graphql etc.

We can add this mechanism but keep your current "custom scalar" based approach too, so module users can select which approach suits their needs better.

**Comment by velias** [comment]
And this might also solve Apollo Federation issue #41 as federation runs in Apollo Server so I believe `validationRules` can be used there (not tested from me).

**Comment by velias** [comment]
@confuser OK, I'm relatively new to nodejs, so challenge accepted ;-)
